services:
  mariadb:
    restart: always
    image: mariadb
    ports:
      - 13306:3306
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb:/data/db
      - ./mongo-init-script.sh:/docker-entrypoint-initdb.d/script.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=echo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
  nginx:
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:host-gateway
#  openvidu-server:
#    image: openvidu/openvidu-server-kms:latest
#    platform: linux/amd64
#    environment:
#      - OPENVIDU_SECRET=MY_SECRET
#      - OPENVIDU_STREAMS_VIDEO_MAX_RECV_BANDWIDTH=1000
#      - OPENVIDU_STREAMS_VIDEO_MIN_RECV_BANDWIDTH=300
#      - OPENVIDU_STREAMS_VIDEO_MAX_SEND_BANDWIDTH=1000
#      - OPENVIDU_STREAMS_VIDEO_MIN_SEND_BANDWIDTH=300
#      - KMS_STUN_IP=stun.l.google.com
#      - KMS_STUN_PORT=19302
#    ports:
#      - "4443:4443"
#      - "3478:3478"
#      - "1935:1935"
#      - "8888:8888"
#    networks:
#      - openvidu-net
  kms:
    image: kurento/kurento-media-server:latest
    platform: linux/amd64
    ports:
      - "8888:8888"
      - "5000-5050:5000-5050/udp"
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
    networks:
      - kurento-net

networks:
  openvidu-net:
    driver: bridge
  kurento-net:
    driver: bridge